// Workflow mining: detect repeated successful trajectories and compile them into a reusable
// asset (a parameterized playbook) + an eval that locks it in. Delivered as a one-change
// candidate so the improvement is only adopted if the eval suite stays green.
import fs from "node:fs";
import path from "node:path";
import { all, get } from "../db.mjs";
import { PATHS, ROOT } from "../config.mjs";

const PLAYBOOK_PATH = path.join(PATHS.playbooks, "coding-util.json");
const SCENARIO_PATH = path.join(ROOT, "evals", "scenarios", "coding-util.mjs");

// The mined artifact: a parameterized "build & verify a coding utility" workflow, generalized
// from the slugify / clamp / isPalindrome successes.
export function buildCodingUtilPlaybook() {
  return {
    name: "coding-util",
    title: "Build & verify a coding utility (mined)",
    mode: "software",
    params: ["spec"],
    description: "Mined from repeated successful util+tests trajectories. Param: spec (what to build).",
    tasks: [
      {
        key: "implement",
        title: "Implement {{spec}}",
        kind: "llm",
        risk_level: "low",
        spec: {
          prompt: "{{spec}}. Create the module and node:test unit tests in the worktree root. Use only Node built-ins + ESM. Tests must pass with `node --test`.",
          worktree: true,
          executor: "claude",
        },
        verify: { method: "node_test" },
      },
      {
        key: "document",
        title: "Document {{spec}}",
        kind: "memory",
        depends_on: ["implement"],
        spec: { knowledge: { key: "util:{{spec}}", kind: "semantic", value: "Implemented and verified: {{spec}}." } },
        verify: { method: "knowledge_present", key: "util:{{spec}}" },
      },
    ],
  };
}

// The generated eval that locks in the mined playbook (deterministic — no LLM).
const SCENARIO_SRC = `// AUTO-GENERATED by workflow mining (src/improve/mine.mjs). Locks in the coding-util playbook.
import { planFromPlaybook } from "../../src/core/planner.mjs";
import { listTasks } from "../../src/core/tasks.mjs";
export default [{
  name: "mined_coding_util_playbook",
  fn: async () => {
    const r = planFromPlaybook("coding-util", { params: { spec: "build a roman numeral encoder" } });
    if (r.taskIds.length !== 2) return { pass: false, detail: \`expected 2 tasks, got \${r.taskIds.length}\` };
    const tasks = listTasks({ goal_id: r.goalId });
    const impl = tasks.find((t) => t.kind === "llm");
    if (!impl || !impl.title.includes("roman numeral encoder")) return { pass: false, detail: "param not substituted into task" };
    const doc = tasks.find((t) => t.kind === "memory");
    if (!doc || (doc.depends_on || []).length !== 1) return { pass: false, detail: "doc task missing dependency on impl" };
    return { pass: true };
  },
}];
`;

// Detect whether the coding-util pattern has recurred enough to be worth compiling.
export function detectCodingUtilPattern() {
  const done = all(`SELECT title, verification_plan FROM tasks WHERE status='done' AND kind IN ('command','llm')`);
  const matches = done.filter((t) => {
    const vp = (t.verification_plan || "").toLowerCase();
    return vp.includes("node_test") || vp.includes("node --test") || /test|util|slug|clamp|palindrome|truncate/i.test(t.title);
  });
  return { count: matches.length, recurred: matches.length >= 2, examples: matches.slice(0, 4).map((t) => t.title) };
}

// One-change candidate that adopts the mined playbook + its eval.
export function codingUtilCandidate(knowledgeProject = null) {
  return {
    name: "mine-coding-util",
    hypothesis: "Repeated util+tests successes generalize to a reusable parameterized playbook.",
    files: [PLAYBOOK_PATH, SCENARIO_PATH],
    knowledgeProject,
    apply: () => {
      fs.mkdirSync(path.dirname(SCENARIO_PATH), { recursive: true });
      fs.writeFileSync(PLAYBOOK_PATH, JSON.stringify(buildCodingUtilPlaybook(), null, 2));
      fs.writeFileSync(SCENARIO_PATH, SCENARIO_SRC);
    },
  };
}

// A deliberately-bad candidate to PROVE auto-revert: it corrupts an existing playbook so a
// known-good eval regresses; the loop must detect the regression and restore the file.
export function brokenDemoCandidate() {
  const target = path.join(PATHS.playbooks, "hello-utility.json");
  return {
    name: "demo-broken-change",
    hypothesis: "(demo) intentionally break a playbook to prove auto-revert on regression.",
    files: [target],
    apply: () => fs.writeFileSync(target, JSON.stringify({ name: "hello-utility", title: "broken", tasks: [] }, null, 2)),
  };
}
